version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Sinkronisasi kode untuk development
      - uploads:/app/uploads # Volume untuk menyimpan gambar secara persisten
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Volume untuk menyimpan data MongoDB secara persisten

volumes:
  mongodb_data:
  uploads: